/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QComboBox *comboBox;
    QPushButton *btn_ip_scan;
    QPushButton *btn_connect_controller;
    QPushButton *btn_disconnect_controller;
    QPushButton *btn_trace_send;
    QLineEdit *ledit_data_file_name;
    QLabel *label;
    QLineEdit *ledit_csv_file_name;
    QLabel *label_2;
    QPushButton *btn_trace_to_xlsx;
    QPushButton *btn_xlsx_to_dat;
    QPushButton *btn_thread_open;
    QPushButton *btn_thread_close;
    QLabel *label_3;
    QLabel *label_4;
    QPushButton *btn_home;
    QLabel *label_5;
    QLabel *label_system_state;
    QLabel *label_6;
    QPushButton *btn_direct_joint_enter;
    QLabel *label_7;
    QLineEdit *ledit_d_j1;
    QLineEdit *ledit_d_j2;
    QLineEdit *ledit_d_j3;
    QLineEdit *ledit_d_j4;
    QLineEdit *ledit_d_j5;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QPushButton *btn_direct_joint_exit;
    QPushButton *btn_direct_joint_send;
    QLabel *label_13;
    QPushButton *btn_jog_enter;
    QPushButton *btn_jog_exit;
    QPushButton *btn_jog_send;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *ledit_jog_x;
    QLineEdit *ledit_jog_y;
    QLineEdit *ledit_jog_z;
    QLineEdit *ledit_jog_phi;
    QLineEdit *ledit_jog_theta;
    QLabel *label_19;
    QPushButton *btn_trace_enter;
    QPushButton *btn_trace_exit;
    QLabel *label_20;
    QLabel *label_motion_mode;
    QLineEdit *ledit_cmd_id;
    QLabel *label_21;
    QPushButton *btn_pause_resume;
    QPushButton *btn_stop;
    QPushButton *btn_emergency_stop;
    QPushButton *btn_error_reset;
    QPushButton *btn_robo_mode_in;
    QLabel *label_22;
    QPushButton *btn_robo_mode_out;
    QComboBox *cbox_speed_level;
    QLabel *label_23;
    QPushButton *btn_ctrl_enter;
    QPushButton *btn_ctrl_exit;
    QPushButton *btn_ctrl_send;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_dL_J1;
    QLabel *label_dL_J2;
    QLabel *label_dL_J3;
    QLabel *label_dL_J4;
    QLabel *label_dL_J5;
    QLabel *label_motor_encoder1;
    QLabel *label_motor_encoder2;
    QLabel *label_motor_encoder3;
    QLabel *label_motor_encoder4;
    QLabel *label_motor_encoder5;
    QLabel *label_motor_torque1;
    QLabel *label_motor_torque2;
    QLabel *label_motor_torque3;
    QLabel *label_motor_torque4;
    QLabel *label_motor_torque5;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_ee_x;
    QLabel *label_ee_y;
    QLabel *label_ee_z;
    QLabel *label_ee_phi;
    QLabel *label_ee_theta;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1011, 711);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        comboBox = new QComboBox(centralwidget);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(42, 50, 141, 25));
        btn_ip_scan = new QPushButton(centralwidget);
        btn_ip_scan->setObjectName(QString::fromUtf8("btn_ip_scan"));
        btn_ip_scan->setGeometry(QRect(200, 50, 93, 28));
        btn_connect_controller = new QPushButton(centralwidget);
        btn_connect_controller->setObjectName(QString::fromUtf8("btn_connect_controller"));
        btn_connect_controller->setGeometry(QRect(310, 50, 111, 28));
        btn_disconnect_controller = new QPushButton(centralwidget);
        btn_disconnect_controller->setObjectName(QString::fromUtf8("btn_disconnect_controller"));
        btn_disconnect_controller->setGeometry(QRect(440, 50, 111, 28));
        btn_trace_send = new QPushButton(centralwidget);
        btn_trace_send->setObjectName(QString::fromUtf8("btn_trace_send"));
        btn_trace_send->setGeometry(QRect(660, 270, 111, 28));
        ledit_data_file_name = new QLineEdit(centralwidget);
        ledit_data_file_name->setObjectName(QString::fromUtf8("ledit_data_file_name"));
        ledit_data_file_name->setGeometry(QRect(802, 330, 91, 31));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(720, 330, 81, 31));
        ledit_csv_file_name = new QLineEdit(centralwidget);
        ledit_csv_file_name->setObjectName(QString::fromUtf8("ledit_csv_file_name"));
        ledit_csv_file_name->setGeometry(QRect(802, 380, 91, 31));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(720, 380, 81, 31));
        btn_trace_to_xlsx = new QPushButton(centralwidget);
        btn_trace_to_xlsx->setObjectName(QString::fromUtf8("btn_trace_to_xlsx"));
        btn_trace_to_xlsx->setGeometry(QRect(900, 330, 91, 31));
        btn_xlsx_to_dat = new QPushButton(centralwidget);
        btn_xlsx_to_dat->setObjectName(QString::fromUtf8("btn_xlsx_to_dat"));
        btn_xlsx_to_dat->setGeometry(QRect(900, 380, 91, 31));
        btn_thread_open = new QPushButton(centralwidget);
        btn_thread_open->setObjectName(QString::fromUtf8("btn_thread_open"));
        btn_thread_open->setGeometry(QRect(590, 330, 121, 31));
        btn_thread_close = new QPushButton(centralwidget);
        btn_thread_close->setObjectName(QString::fromUtf8("btn_thread_close"));
        btn_thread_close->setGeometry(QRect(590, 380, 121, 31));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(40, 20, 201, 19));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(40, 100, 69, 19));
        btn_home = new QPushButton(centralwidget);
        btn_home->setObjectName(QString::fromUtf8("btn_home"));
        btn_home->setGeometry(QRect(40, 130, 141, 31));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(660, 10, 101, 21));
        label_system_state = new QLabel(centralwidget);
        label_system_state->setObjectName(QString::fromUtf8("label_system_state"));
        label_system_state->setGeometry(QRect(780, 10, 211, 19));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(40, 190, 111, 31));
        btn_direct_joint_enter = new QPushButton(centralwidget);
        btn_direct_joint_enter->setObjectName(QString::fromUtf8("btn_direct_joint_enter"));
        btn_direct_joint_enter->setGeometry(QRect(170, 190, 111, 28));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(200, 100, 101, 19));
        ledit_d_j1 = new QLineEdit(centralwidget);
        ledit_d_j1->setObjectName(QString::fromUtf8("ledit_d_j1"));
        ledit_d_j1->setGeometry(QRect(90, 240, 61, 25));
        ledit_d_j2 = new QLineEdit(centralwidget);
        ledit_d_j2->setObjectName(QString::fromUtf8("ledit_d_j2"));
        ledit_d_j2->setGeometry(QRect(90, 280, 61, 25));
        ledit_d_j3 = new QLineEdit(centralwidget);
        ledit_d_j3->setObjectName(QString::fromUtf8("ledit_d_j3"));
        ledit_d_j3->setGeometry(QRect(90, 320, 61, 25));
        ledit_d_j4 = new QLineEdit(centralwidget);
        ledit_d_j4->setObjectName(QString::fromUtf8("ledit_d_j4"));
        ledit_d_j4->setGeometry(QRect(90, 360, 61, 25));
        ledit_d_j5 = new QLineEdit(centralwidget);
        ledit_d_j5->setObjectName(QString::fromUtf8("ledit_d_j5"));
        ledit_d_j5->setGeometry(QRect(90, 400, 61, 25));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(40, 240, 41, 21));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(40, 280, 41, 21));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(40, 320, 41, 21));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(40, 360, 41, 21));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(40, 400, 41, 21));
        btn_direct_joint_exit = new QPushButton(centralwidget);
        btn_direct_joint_exit->setObjectName(QString::fromUtf8("btn_direct_joint_exit"));
        btn_direct_joint_exit->setGeometry(QRect(170, 230, 111, 28));
        btn_direct_joint_send = new QPushButton(centralwidget);
        btn_direct_joint_send->setObjectName(QString::fromUtf8("btn_direct_joint_send"));
        btn_direct_joint_send->setGeometry(QRect(170, 270, 111, 28));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(320, 190, 69, 31));
        btn_jog_enter = new QPushButton(centralwidget);
        btn_jog_enter->setObjectName(QString::fromUtf8("btn_jog_enter"));
        btn_jog_enter->setGeometry(QRect(450, 190, 111, 28));
        btn_jog_exit = new QPushButton(centralwidget);
        btn_jog_exit->setObjectName(QString::fromUtf8("btn_jog_exit"));
        btn_jog_exit->setGeometry(QRect(450, 230, 111, 28));
        btn_jog_send = new QPushButton(centralwidget);
        btn_jog_send->setObjectName(QString::fromUtf8("btn_jog_send"));
        btn_jog_send->setGeometry(QRect(450, 270, 111, 28));
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(320, 240, 41, 19));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(320, 280, 41, 19));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(320, 320, 41, 19));
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(320, 360, 51, 19));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(320, 400, 51, 19));
        ledit_jog_x = new QLineEdit(centralwidget);
        ledit_jog_x->setObjectName(QString::fromUtf8("ledit_jog_x"));
        ledit_jog_x->setGeometry(QRect(370, 240, 61, 25));
        ledit_jog_y = new QLineEdit(centralwidget);
        ledit_jog_y->setObjectName(QString::fromUtf8("ledit_jog_y"));
        ledit_jog_y->setGeometry(QRect(370, 280, 61, 25));
        ledit_jog_z = new QLineEdit(centralwidget);
        ledit_jog_z->setObjectName(QString::fromUtf8("ledit_jog_z"));
        ledit_jog_z->setGeometry(QRect(370, 320, 61, 25));
        ledit_jog_phi = new QLineEdit(centralwidget);
        ledit_jog_phi->setObjectName(QString::fromUtf8("ledit_jog_phi"));
        ledit_jog_phi->setGeometry(QRect(370, 360, 61, 25));
        ledit_jog_theta = new QLineEdit(centralwidget);
        ledit_jog_theta->setObjectName(QString::fromUtf8("ledit_jog_theta"));
        ledit_jog_theta->setGeometry(QRect(370, 400, 61, 25));
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(600, 190, 69, 31));
        btn_trace_enter = new QPushButton(centralwidget);
        btn_trace_enter->setObjectName(QString::fromUtf8("btn_trace_enter"));
        btn_trace_enter->setGeometry(QRect(660, 190, 111, 28));
        btn_trace_exit = new QPushButton(centralwidget);
        btn_trace_exit->setObjectName(QString::fromUtf8("btn_trace_exit"));
        btn_trace_exit->setGeometry(QRect(660, 230, 111, 28));
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(660, 40, 111, 19));
        label_motion_mode = new QLabel(centralwidget);
        label_motion_mode->setObjectName(QString::fromUtf8("label_motion_mode"));
        label_motion_mode->setGeometry(QRect(780, 40, 211, 19));
        ledit_cmd_id = new QLineEdit(centralwidget);
        ledit_cmd_id->setObjectName(QString::fromUtf8("ledit_cmd_id"));
        ledit_cmd_id->setGeometry(QRect(310, 130, 111, 31));
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(310, 100, 69, 19));
        btn_pause_resume = new QPushButton(centralwidget);
        btn_pause_resume->setObjectName(QString::fromUtf8("btn_pause_resume"));
        btn_pause_resume->setGeometry(QRect(660, 70, 111, 41));
        btn_stop = new QPushButton(centralwidget);
        btn_stop->setObjectName(QString::fromUtf8("btn_stop"));
        btn_stop->setGeometry(QRect(660, 120, 111, 41));
        btn_emergency_stop = new QPushButton(centralwidget);
        btn_emergency_stop->setObjectName(QString::fromUtf8("btn_emergency_stop"));
        btn_emergency_stop->setGeometry(QRect(790, 70, 201, 41));
        btn_error_reset = new QPushButton(centralwidget);
        btn_error_reset->setObjectName(QString::fromUtf8("btn_error_reset"));
        btn_error_reset->setGeometry(QRect(790, 120, 201, 41));
        btn_robo_mode_in = new QPushButton(centralwidget);
        btn_robo_mode_in->setObjectName(QString::fromUtf8("btn_robo_mode_in"));
        btn_robo_mode_in->setGeometry(QRect(440, 130, 91, 31));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(450, 100, 111, 19));
        btn_robo_mode_out = new QPushButton(centralwidget);
        btn_robo_mode_out->setObjectName(QString::fromUtf8("btn_robo_mode_out"));
        btn_robo_mode_out->setGeometry(QRect(540, 130, 91, 31));
        cbox_speed_level = new QComboBox(centralwidget);
        cbox_speed_level->setObjectName(QString::fromUtf8("cbox_speed_level"));
        cbox_speed_level->setGeometry(QRect(200, 130, 91, 31));
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(800, 190, 69, 31));
        btn_ctrl_enter = new QPushButton(centralwidget);
        btn_ctrl_enter->setObjectName(QString::fromUtf8("btn_ctrl_enter"));
        btn_ctrl_enter->setGeometry(QRect(880, 187, 111, 31));
        btn_ctrl_exit = new QPushButton(centralwidget);
        btn_ctrl_exit->setObjectName(QString::fromUtf8("btn_ctrl_exit"));
        btn_ctrl_exit->setGeometry(QRect(880, 230, 111, 31));
        btn_ctrl_send = new QPushButton(centralwidget);
        btn_ctrl_send->setObjectName(QString::fromUtf8("btn_ctrl_send"));
        btn_ctrl_send->setGeometry(QRect(880, 270, 111, 31));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(40, 450, 101, 21));
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(40, 490, 111, 19));
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(40, 520, 111, 19));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(40, 550, 111, 19));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(40, 580, 111, 19));
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(40, 610, 111, 19));
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(290, 490, 131, 19));
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(290, 520, 131, 19));
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(290, 550, 131, 19));
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(290, 580, 131, 19));
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(290, 610, 131, 19));
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(550, 490, 131, 19));
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(550, 520, 131, 19));
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(550, 550, 131, 19));
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(550, 580, 131, 19));
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(550, 610, 131, 19));
        label_dL_J1 = new QLabel(centralwidget);
        label_dL_J1->setObjectName(QString::fromUtf8("label_dL_J1"));
        label_dL_J1->setGeometry(QRect(160, 490, 111, 19));
        label_dL_J2 = new QLabel(centralwidget);
        label_dL_J2->setObjectName(QString::fromUtf8("label_dL_J2"));
        label_dL_J2->setGeometry(QRect(160, 520, 111, 19));
        label_dL_J3 = new QLabel(centralwidget);
        label_dL_J3->setObjectName(QString::fromUtf8("label_dL_J3"));
        label_dL_J3->setGeometry(QRect(160, 550, 111, 19));
        label_dL_J4 = new QLabel(centralwidget);
        label_dL_J4->setObjectName(QString::fromUtf8("label_dL_J4"));
        label_dL_J4->setGeometry(QRect(160, 580, 111, 19));
        label_dL_J5 = new QLabel(centralwidget);
        label_dL_J5->setObjectName(QString::fromUtf8("label_dL_J5"));
        label_dL_J5->setGeometry(QRect(160, 610, 111, 19));
        label_motor_encoder1 = new QLabel(centralwidget);
        label_motor_encoder1->setObjectName(QString::fromUtf8("label_motor_encoder1"));
        label_motor_encoder1->setGeometry(QRect(420, 490, 121, 19));
        label_motor_encoder2 = new QLabel(centralwidget);
        label_motor_encoder2->setObjectName(QString::fromUtf8("label_motor_encoder2"));
        label_motor_encoder2->setGeometry(QRect(420, 520, 121, 19));
        label_motor_encoder3 = new QLabel(centralwidget);
        label_motor_encoder3->setObjectName(QString::fromUtf8("label_motor_encoder3"));
        label_motor_encoder3->setGeometry(QRect(420, 550, 121, 19));
        label_motor_encoder4 = new QLabel(centralwidget);
        label_motor_encoder4->setObjectName(QString::fromUtf8("label_motor_encoder4"));
        label_motor_encoder4->setGeometry(QRect(420, 580, 121, 19));
        label_motor_encoder5 = new QLabel(centralwidget);
        label_motor_encoder5->setObjectName(QString::fromUtf8("label_motor_encoder5"));
        label_motor_encoder5->setGeometry(QRect(420, 610, 121, 19));
        label_motor_torque1 = new QLabel(centralwidget);
        label_motor_torque1->setObjectName(QString::fromUtf8("label_motor_torque1"));
        label_motor_torque1->setGeometry(QRect(680, 490, 111, 19));
        label_motor_torque2 = new QLabel(centralwidget);
        label_motor_torque2->setObjectName(QString::fromUtf8("label_motor_torque2"));
        label_motor_torque2->setGeometry(QRect(680, 520, 111, 19));
        label_motor_torque3 = new QLabel(centralwidget);
        label_motor_torque3->setObjectName(QString::fromUtf8("label_motor_torque3"));
        label_motor_torque3->setGeometry(QRect(680, 550, 111, 19));
        label_motor_torque4 = new QLabel(centralwidget);
        label_motor_torque4->setObjectName(QString::fromUtf8("label_motor_torque4"));
        label_motor_torque4->setGeometry(QRect(680, 580, 111, 19));
        label_motor_torque5 = new QLabel(centralwidget);
        label_motor_torque5->setObjectName(QString::fromUtf8("label_motor_torque5"));
        label_motor_torque5->setGeometry(QRect(680, 610, 111, 19));
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(760, 450, 141, 19));
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(760, 550, 41, 19));
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(760, 490, 41, 19));
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(760, 610, 51, 19));
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(760, 580, 51, 19));
        label_45 = new QLabel(centralwidget);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(760, 520, 41, 19));
        label_ee_x = new QLabel(centralwidget);
        label_ee_x->setObjectName(QString::fromUtf8("label_ee_x"));
        label_ee_x->setGeometry(QRect(830, 490, 101, 19));
        label_ee_y = new QLabel(centralwidget);
        label_ee_y->setObjectName(QString::fromUtf8("label_ee_y"));
        label_ee_y->setGeometry(QRect(830, 520, 101, 19));
        label_ee_z = new QLabel(centralwidget);
        label_ee_z->setObjectName(QString::fromUtf8("label_ee_z"));
        label_ee_z->setGeometry(QRect(830, 550, 101, 19));
        label_ee_phi = new QLabel(centralwidget);
        label_ee_phi->setObjectName(QString::fromUtf8("label_ee_phi"));
        label_ee_phi->setGeometry(QRect(830, 580, 101, 19));
        label_ee_theta = new QLabel(centralwidget);
        label_ee_theta->setObjectName(QString::fromUtf8("label_ee_theta"));
        label_ee_theta->setGeometry(QRect(830, 610, 101, 19));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1011, 25));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        btn_ip_scan->setText(QCoreApplication::translate("MainWindow", "IP SCAN", nullptr));
        btn_connect_controller->setText(QCoreApplication::translate("MainWindow", "Connect", nullptr));
        btn_disconnect_controller->setText(QCoreApplication::translate("MainWindow", "Disconnect", nullptr));
        btn_trace_send->setText(QCoreApplication::translate("MainWindow", "SEND", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "File Name", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Csv Name", nullptr));
        btn_trace_to_xlsx->setText(QCoreApplication::translate("MainWindow", "Dat to Csv", nullptr));
        btn_xlsx_to_dat->setText(QCoreApplication::translate("MainWindow", "Csv to Dat", nullptr));
        btn_thread_open->setText(QCoreApplication::translate("MainWindow", "Thread Open", nullptr));
        btn_thread_close->setText(QCoreApplication::translate("MainWindow", "Thread Close", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Connection", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Home", nullptr));
        btn_home->setText(QCoreApplication::translate("MainWindow", "Home", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "System State", nullptr));
        label_system_state->setText(QCoreApplication::translate("MainWindow", "Disconnected", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Direct Joint", nullptr));
        btn_direct_joint_enter->setText(QCoreApplication::translate("MainWindow", "ENTER", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Speed Level", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "1(um)", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "2(um)", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "3(um)", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "4(um)", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "5(um)", nullptr));
        btn_direct_joint_exit->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        btn_direct_joint_send->setText(QCoreApplication::translate("MainWindow", "SEND", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Cart Jog", nullptr));
        btn_jog_enter->setText(QCoreApplication::translate("MainWindow", "ENTER", nullptr));
        btn_jog_exit->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        btn_jog_send->setText(QCoreApplication::translate("MainWindow", "SEND", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "x(um)", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "y(um)", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "z(um)", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "\317\206(\")", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "\316\270(\")", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Trace", nullptr));
        btn_trace_enter->setText(QCoreApplication::translate("MainWindow", "ENTER", nullptr));
        btn_trace_exit->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Motion Mode", nullptr));
        label_motion_mode->setText(QCoreApplication::translate("MainWindow", "None", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Cmd", nullptr));
        btn_pause_resume->setText(QCoreApplication::translate("MainWindow", "PAUSE", nullptr));
        btn_stop->setText(QCoreApplication::translate("MainWindow", "STOP", nullptr));
        btn_emergency_stop->setText(QCoreApplication::translate("MainWindow", "EMERGENCY", nullptr));
        btn_error_reset->setText(QCoreApplication::translate("MainWindow", "RESET", nullptr));
        btn_robo_mode_in->setText(QCoreApplication::translate("MainWindow", "ENTER", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "Robot Mode", nullptr));
        btn_robo_mode_out->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Ctrl Trace", nullptr));
        btn_ctrl_enter->setText(QCoreApplication::translate("MainWindow", "ENTER", nullptr));
        btn_ctrl_exit->setText(QCoreApplication::translate("MainWindow", "EXIT", nullptr));
        btn_ctrl_send->setText(QCoreApplication::translate("MainWindow", "SEND", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Robot State", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "\316\224L Joint1(um)", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "\316\224L Joint2(um)", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "\316\224L Joint3(um)", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "\316\224L Joint4(um)", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "\316\224L Joint5(um)", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "Motor Encoder1", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "Motor Encoder2", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "Motor Encoder3", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "Motor Encoder4", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Motor Encoder5", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Motor Torque1", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Motor Torque2", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Motor Torque3", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Motor Torque4", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Motor Torque5", nullptr));
        label_dL_J1->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_dL_J2->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_dL_J3->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_dL_J4->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_dL_J5->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_encoder1->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_encoder2->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_encoder3->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_encoder4->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_encoder5->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_torque1->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_torque2->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_torque3->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_torque4->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_motor_torque5->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "End Effector", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "z(um)", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "x(um)", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "\316\270(\")", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "\317\206(\")", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "y(um)", nullptr));
        label_ee_x->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_ee_y->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_ee_z->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_ee_phi->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_ee_theta->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
